name: API Production
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy via SSH
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: 'ec2-3-35-233-178.ap-northeast-2.compute.amazonaws.com'
          USER_NAME: 'ec2-user'
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd boards
            git pull origin main &&
            yarn install &&
            pm2 restart api-prod
          '
